<?php require('templates/header.phtml') ?>

<!-- PAGE DATA FOUND BELOW -->
<section id="background" class="about-us-section py-5">
    <div class="container">
        <div  id="aboutUsSection1" class="row">
            <div class="col-md-6">
                <h3>About Us</h3>
                <p>Welcome to CODE SCULPTOR, your ultimate destination for browser-based code refactoring! Our journey began with a simple idea: to create a powerful yet user-friendly tool that simplifies the process of code refactoring, making it accessible to developers of all levels.</p>
                <p>Driven by our passion for coding and a desire to streamline development workflows, we embarked on a mission to build a platform that empowers developers to write cleaner, more efficient code. With a team of dedicated programmers and designers, we set out to create a tool that not only identifies areas for improvement in codebases but also provides actionable suggestions for optimization.</p>
            </div>
            <div id="codingGif" class="col-md-6">
                <img src="images/coding.gif" class="img-fluid" alt="Image Illustrating Coding within the IT Industry">
                <p class="text-muted italic">Image credit: Kive.ai/app - Jacqueleen Eng </p>
            </div>
        </div>
        <div  id="aboutUsSection2" class="row">
            <div class="col-md-6">
                <p>Today, CODE SCULPTOR stands as a testament to our dedication to advancing the field of software development. With a robust set of features and an intuitive user interface, our platform empowers developers to refactor code with ease, saving time and resources while promoting best practices in coding standards.</p>
                <p>Whether you're a seasoned developer looking to optimize a complex codebase or a newcomer seeking guidance on best coding practices, CODE SCULPTOR is here to support you every step of the way. Join us on our mission to elevate the coding experience and unlock the full potential of your projects.</p>
                <p>Thank you for being part of our journey. Together, let's shape the future of code refactoring and pave the way for a more efficient and enjoyable coding experience.</p>
            </div>
        </div>
    </div>
</section>
<!-- End About Us Section -->

<?php require('templates/footer.phtml') ?>
