<?php require('templates/header.phtml') ?>

<!-- PAGE DATA FOUND BELOW -->
<div id="fixedBackground">
    <div class="container py-5">
        <h1 class="text-center mb-4">Contact Me</h1>
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <form action="#" method="POST">
                    <div class="form-group">
                        <label for="name">Your Name:</label>
                        <!-- populate the value of the input field with the username if set for user's convenience -->
                        <input type="text" class="form-control" id="name" name="name" required
                               value="<?php echo isset($_SESSION['username']) ? $_SESSION['username'] : ''; ?>">
                    </div>
                    <div class="form-group">
                        <label for="email">Your Email:</label>
                        <input type="email" class="form-control" id="email" name="email" required>
                    </div>
                    <div class="form-group">
                        <label for="message">Message:</label>
                        <!-- Populate the value of the textarea with the default message -->
                        <textarea class="form-control" id="message" name="message" rows="5" required><?php echo isset($_SESSION['username']) ? "Hello, {$_SESSION['username']} here!\n\nI really liked how / I think you could improve the experience with..." : ''; ?></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary mt-3">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

<?php require('templates/footer.phtml') ?>
