<?php require('templates/header.phtml') ?>

<!-- PAGE DATA FOUND BELOW -->
<div id="background">
    <div id="text-container">
        <h1>CODE SCULPTOR</h1>
        <h2>Browser-Based Code Refactoring Made Simple</h2>
    </div>
    <div id="image-container">
        <img src="images/codingImage.png" alt="Code Illustration">
    </div>
</div>
<div class="container">
    <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">
        <div class="col">
            <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg" style="background-image: url('unsplash-photo-1.jpg');">
                <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
                    <a href="refactor.php">
                        <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">Code Refactoring</h3>
                        <ul class="d-flex list-unstyled mt-auto">
                            <li class="me-auto">
                            </li>
                            <li class="d-flex align-items-center me-3">
                                <small>Last Updated</small>
                            </li>
                            <li class="d-flex align-items-center">
                                <small>09/02/2024</small>
                            </li>
                        </ul>
                    </a>
                </div>
            </div>
        </div>

        <div class="col">
            <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg" style="background-image: url('unsplash-photo-2.jpg');">
                <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
                    <a href="about.php">
                        <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">About Us</h3>
                        <ul class="d-flex list-unstyled mt-auto">
                            <li class="me-auto">
                            </li>
                            <li class="d-flex align-items-center me-3">
                                <small>Last Updated</small>
                            </li>
                            <li class="d-flex align-items-center">
                                <small>01/02/2024</small>
                            </li>
                        </ul>
                    </a>
                </div>
            </div>
        </div>

        <div class="col">
            <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg" style="background-image: url('unsplash-photo-3.jpg');">
                <div class="d-flex flex-column h-100 p-5 pb-3 text-shadow-1">
                    <a href="contact.php">
                        <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">Contact Us</h3>
                        <ul class="d-flex list-unstyled mt-auto">
                            <li class="me-auto">
                            </li>
                            <li class="d-flex align-items-center me-3">
                                <small>Last Updated</small>
                            </li>
                            <li class="d-flex align-items-center">
                                <small>01/02/2024</small>
                            </li>
                        </ul>
                    <a/>
                </div>
            </div>
        </div>
    </div>
</div>

<?php require('templates/footer.phtml') ?>
