<?php //require('templates/header.phtml') ?>
<!---->
<!-- User Information -->
<!--<div class="user-info">-->
<!--    <h2>Welcome, --><?php //echo $_SESSION['username']; ?><!--</h2>-->
    <!-- Logout Button -->
<!--    <form action="../logoutPage.php" method="POST">-->
<!--        <input type="submit" name="logoutButton" value="Logout">-->
<!--    </form>-->
<!--</div>-->
<!---->
<!-- Include Logout Button -->
<?php //require('templates/footer.phtml') ?>
