<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <link href="css/myStyle.css" rel="stylesheet">

    <title>Browser Based Code Refactoring - <?php echo $view->pageTitle; ?></title>
</head>

<body class="d-flex flex-column h-100">

<!-- HEADER AREA BELOW -->
<!-- TODO Implement the header in the header.phtml doc -->
<header>
</header>

<!-- ACTUAL PAGE CONTENT TO BE FOUND BELOW -->
<!-- TODO Check over to see if these bootstrap settings look good or not-->
<main class="flex-shrink-0">

    <div class="container-fluid">
        <div  class="row-fluid">
        </div>

        <div class="row">
            <section id="content" class="col-xs-6 col-sm-9 col-md-12">