<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="My Final Year Project Regarding a Browser-Based Code Refactoring Tool">
    <meta name="author" content="Miroslav Hajas">

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <link href="css/myStyle.css" rel="stylesheet">

    <title><?php echo $view->pageTitle; ?></title>
</head>
<body class="d-flex flex-column h-100">
<header>
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">CODE SCULPTOR</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li id="hoverable" class="nav-item">
                        <a class="nav-link" href="index.php">Home</a>
                    </li>
                    <li id="hoverable" class="nav-item">
                        <a class="nav-link" href="refactor.php">Refactor</a>
                    </li>
                    <li id="hoverable" class="nav-item">
                        <a class="nav-link" href="#">About</a>
                    </li>
                    <li id="hoverable" class="nav-item">
                        <a class="nav-link" href="#">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<!-- ACTUAL PAGE CONTENT TO BE FOUND BELOW -->
<!-- TODO Check over to see if these bootstrap settings look good or not-->
<main class="flex-shrink-0">
    <div class="container-fluid">
        <div  class="row-fluid">
        </div>
        <div class="row">
            <section id="content" class="col-xs-6 col-sm-9 col-md-12">
