<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="My Final Year Project Regarding a Browser-Based Code Refactoring Tool">
    <meta name="author" content="Miroslav Hajas">

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link href="css/myStyle.css" rel="stylesheet">

    <!-- Implementation of CodeMirror below -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.3/codemirror.min.css">
    <!-- Latest compiled JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.3/codemirror.min.js"></script>
    <!-- Match Brackets Add-on -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.3/addon/edit/matchbrackets.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.0/theme/dracula.min.css">
    <!-- JavaScript source tage -->
    <script src="../../js/refactor.js" type="module"></script>

    <title><?php echo $view->pageTitle; ?></title>
    <!-- Begin session start from header to use cookies and login / logout functionality -->
    <?php // check if the session has already been started
    if (session_status() === PHP_SESSION_NONE) {
        session_start();
    } ?>

</head>
<body class="d-flex flex-column h-100">
<header>
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="navbar-brand">CODE SCULPTOR</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <!-- Conditional display of login/logout button -->
                    <?php if(isset($_SESSION['username'])): ?>
                        <!-- If logged in, display logout button -->
                        <li id="hoverable" class="nav-item">
                            <a class="nav-link text-primary" href="../../loginPage.php">Logout</a>
                        </li>
                    <?php else: ?>
                        <!-- If not logged in, display login button -->
                        <li id="hoverable" class="nav-item">
                            <a class="nav-link text-primary" href="../../loginPage.php">Login</a>
                        </li>
                    <?php endif; ?>
                    <!-- Other navigation links -->
                    <li id="hoverable" class="nav-item">
                        <a class="nav-link" href="index.php">Home</a>
                    </li>
                    <li id="hoverable" class="nav-item">
                        <a class="nav-link" href="refactor.php">Refactor</a>
                    </li>
                    <li id="hoverable" class="nav-item">
                        <a class="nav-link" href="about.php">About</a>
                    </li>
                    <li id="hoverable" class="nav-item">
                        <a class="nav-link" href="contact.php">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<!-- PHP STATEMENT USED FOR TESTING ONLY -->
<?php //echo $_SESSION['username'] ?>

<!-- ACTUAL PAGE CONTENT TO BE FOUND BELOW -->
<!-- TODO Check over to see if these bootstrap settings look good or not-->
<main class="flex-shrink-0">
    <div class="container-fluid">
        <div  class="row-fluid">
        </div>
        <div class="row">
            <section id="content" class="col-xs-6 col-sm-9 col-md-12">
